apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxseer-rca-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluxseer-rca-observability
  template:
    metadata:
      labels:
        app: fluxseer-rca-observability
    spec:
      containers:
        - name: observability
          image: fluxseer/fluxseer-rca/demo-observability:v0.2.0-beta.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: fluxseer-rca-observability
spec:
  selector:
    app: fluxseer-rca-observability
  ports:
    - name: http
      port: 8080
      targetPort: 8080
