apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluxseer-rca-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluxseer-rca-manager-role
subjects:
  - kind: ServiceAccount
    name: fluxseer-rca-controller-manager
    namespace: fluxseer-rca-system
