namespace: fluxagent-demo

resources:
  - ../../config/default
  - ../sample-app
  - ../fake-observability

patches:
  - path: manager-demo-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: fluxagent-controller-manager

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
