apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxseer-rca-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          image: fluxseer/fluxseer-rca/operator:v0.2.0-beta.1
          env:
            - name: FLUXSEER_RCA_WEBHOOK_URL
              value: http://fluxseer-rca-observability:8080/demo/webhook
          args:
            - --enable-remediation=false
