{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluxseer-rca.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluxseer-rca.labels" . | nindent 4 }}
{{- end }}
